config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    invitations: 'users/invitations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :accounts
  resources :plans, except: [:destroy]
  resources :products, except: [:destroy]

  get 'dashboard', to: 'dashboard#index'
  scope 'settings', as: 'settings' do
    resources :billing, only: [:index], controller: 'settings/billing'
    resources :subscriptions, except: [:new], controller: 'settings/subscriptions'
  end

  authenticate :user, ->(u) { u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'welcome#index'
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :product
  has_many :subscription_items
  has_many :subscriptions, through: :subscription_items

  scope :displayable, -> { where(displayable: true) }
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  skip_before_action :set_current_account
  before_action :set_plan, only: [:show, :destroy, :edit, :update]
  authorize_resource

  # GET /plans
  def index
    @plans = Plan.all
  end

  # GET /plans/:id
  def show; end

  # GET /plans/new
  def new
    @plan = Plan.new
    @products = Product.all
  end

  # GET /plans/:id/edit
  def edit; end

  # POST /plans
  def create
    result = Services.create_plan.call(plan_params: create_params)
    @plan = result.plan

    respond_to do |format|
      if result.success?
        format.html { redirect_to @plan, notice: 'Plan was successfully created' }
      else
        format.html { render :new }
      end
    end
  end

  # PUT/PATCH /plans/:id
  def update
    respond_to do |format|
      if @plan.update(update_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated' }
      else
        format.html { render :edit }
      end
    end
  end

  private

  def set_plan
    @plan = Plan.find(params[:id])
  end

  def create_params
    params.require(:plan).permit(
      :name, :product_id, :amount, :currency, :interval, :interval_count, :trial_period_days,
      :active, :displayable
    )
  end

  def update_params
    params.require(:plan).permit(:active, :displayable)
  end
end

app/views/plans/edit.html.erb
<h1>Edit Plan</h1>

<%= form_with(model: @plan, local: true) do |form| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@plan.errors.count, "error") %> prohibited this account from being saved:
      </h2>
      <ul>
      <% @plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p><strong>Product:</strong><%= @plan.product.name %></p>
  <p><strong>Name:</strong><%= @plan.name %></p>
  <p><strong>Amount:</strong><%= @plan.amount %></p>
  <p><strong>Interval:</strong><%= @plan.interval %></p>
  <p><strong>Interval Count:</strong><%= @plan.interval_count %></p>
  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="field">
    <%= form.label :displayable %>
    <%= form.check_box :displayable %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<h1>Plans</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Stripe ID</th>
      <th>Amount</th>
      <th>Interval</th>
      <th>Active</th>
      <th>Displayable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plans.each do |plan| %>
      <tr>
        <td><%= plan.name %></td>
        <td><%= plan.stripe_id %></td>
        <td><%= plan.amount %></td>
        <td><%= plan.interval %></td>
        <td><%= plan.active %></td>
        <td><%= plan.displayable %></td>
        <td><%= link_to 'Show', plan %></td>
        <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
        <td><%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plan', new_plan_path %>

app/views/plans/new.html.erb
<h1>New Plan</h1>

<%= form_with(model: @plan, local: true) do |form| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@plan.errors.count, "error") %> prohibited this account from being saved:
      </h2>
      <ul>
      <% @plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product %>
    <%= form.collection_select(:product_id, @products, :id, :name) %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>

  <div class="field">
    <%= form.label :interval %>
    <%= form.text_field :interval %>
  </div>

  <div class="field">
    <%= form.label :interval_count %>
    <%= form.number_field :interval_count %>
  </div>

  <div class="field">
    <%= form.label :trial_period_days %>
    <%= form.number_field :trial_period_days %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="field">
    <%= form.label :displayable %>
    <%= form.check_box :displayable %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', plans_path %>

app/views/plans/show.html.erb
<p><strong>Name:</strong>               <%= @plan.name %></p>
<p><strong>Stripe ID:</strong>          <%= @plan.stripe_id %></p>
<p><strong>Amount:</strong>             <%= @plan.amount %></p>
<p><strong>Currency:</strong>           <%= @plan.currency %></p>
<p><strong>Interval:</strong>           <%= @plan.interval %></p>
<p><strong>Interval Count:</strong>     <%= @plan.interval_count %></p>
<p><strong>Trial Period Days:</strong>  <%= @plan.trial_period_days %></p>
<p><strong>Active:</strong>             <%= @plan.active %></p>
<p><strong>Displayable:</strong>        <%= @plan.displayable %></p>

<%= link_to 'Back', plans_path %>
<%= link_to 'Edit', edit_plan_path(@plan) %>