config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    invitations: 'users/invitations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :accounts
  resources :plans, except: [:destroy]
  resources :products, except: [:destroy]

  get 'dashboard', to: 'dashboard#index'
  scope 'settings', as: 'settings' do
    resources :billing, only: [:index], controller: 'settings/billing'
    resources :subscriptions, except: [:new], controller: 'settings/subscriptions'
  end

  authenticate :user, ->(u) { u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'welcome#index'
end

app/views/layouts/authenticated/_admin_sidebar.html.erb
  <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Accounts">
    <a class="nav-link" href="<%= accounts_path %>">
      <i class="fa fa-fw fa-building"></i>
      <span class="nav-link-text">Accounts</span>
    </a>
  </li>
  <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Products">
    <a class="nav-link" href="<%= products_path %>">
      <i class="fa fa-fw fa-folder-open"></i>
      <span class="nav-link-text">Products</span>
    </a>
  </li>
  <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Plans">
    <a class="nav-link" href="<%= plans_path %>">
      <i class="fa fa-fw fa-file"></i>
      <span class="nav-link-text">Plans</span>
    </a>
  </li>
  <li class="nav-item" data-toggle="tooltip" data-placement="right" title="SideKiq">
    <a class="nav-link" href="<%= sidekiq_web_path %>">
      <i class="fa fa-fw fa-line-chart"></i>
      <span class="nav-link-text">SideKiq</span>
    </a>
  </li>

app/views/layouts/authenticated/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class='alert alert-fixed <%= flash_class(key) %> alert-dismissible fade show'>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
     <span aria-hidden="true">&times;</span>
    </button>
    <%= value %>
  </div>
<% end %>

app/views/layouts/authenticated/_footer.html.erb
<footer class="sticky-footer">
  <div class="container">
    <div class="text-center">
      <small>Copyright © Your Website 2018</small>
    </div>
  </div>
</footer>

app/views/layouts/authenticated/_frame.html.erb
<body class="authenticated fixed-nav sticky-footer bg-dark" data-controller="<%= controller_name %>" data-action="<%= action_name %>" id="page-top">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <%= link_to 'RMST App', default_dashboard, class: 'navbar-brand' %>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <%= render 'layouts/authenticated/sidebar' %>
      <%= render 'layouts/authenticated/header' %>
    </div>
  </nav>
<div class="content-wrapper">
  <div class='container-fluid'>
    <%= render 'layouts/authenticated/flash_messages' %>
    <%= yield %>
  </div>
  <%= render 'layouts/authenticated/footer' %>
</div>
</body>

app/views/layouts/authenticated/_header.html.erb
<ul class="navbar-nav ml-auto">
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" id="userDropdown" href="#" data-toggle="dropdown" aria-haspopup="false" aria-expanded="false">
      <i class="fa fa-fw fa-cogs"></i>
        <%= current_user.name %>
      </span>
    </a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
      <h6 class="dropdown-header">Settings:</h6>
      <%= link_to 'Profile', edit_user_registration_path,               class: 'dropdown-item' %>
      <%= link_to 'Account', account_path(current_user.account),        class: 'dropdown-item' %>
      <%= link_to 'Billing', settings_billing_index_path,               class: 'dropdown-item' %>
      <%= link_to 'Logout', destroy_user_session_path,                  class: 'dropdown-item', method: :delete %>
      </div>
  </li>
</ul>

app/views/layouts/authenticated/_sidebar.html.erb
<ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
  <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
    <a class="nav-link" href="<%= default_dashboard %>">
      <i class="fa fa-fw fa-dashboard"></i>
      <span class="nav-link-text">Dashboard</span>
    </a>
  </li>
  <%= render 'layouts/authenticated/admin_sidebar' if current_user.is_admin? %>
</ul>
<ul class="navbar-nav sidenav-toggler">
  <li class="nav-item">
    <a class="nav-link text-center" id="sidenavToggler">
      <i class="fa fa-fw fa-angle-left"></i>
    </a>
  </li>
</ul>